### ISSUE TITLE
SonarQube doesn't start with plugin

### ISSUE THREAD

**Issue by andrexus** [Cognifide/AEM-Rules-for-SonarQube#1]
I have an issue with the plugin. Sonar starts the first time, creates database and works just fine. But the second time it doesn't start. There is not much info in log. I found a few lines with error messages.
```
ERROR web[o.a.c.c.C.[.[.[/]] Exception sending context initialized event to listener instance of class org.sonar.server.platform.PlatformServletContextListener
java.lang.NoClassDefFoundError: org/sonar/plugins/java/api/CheckRegistrar
ERROR web[jruby.rack] initialization failed
ERROR web[o.a.c.c.StandardContext] Error listenerStart
ERROR web[o.a.c.c.StandardContext] Context [] startup failed due to previous errors
```

**Comment by chutch** [comment]
Please make sure you run SonarQube with Java 3.3 plugin.

**Comment by andrexus** [comment]
This is my list of installed plugins:
- aemrules.jar
- sonar-java-plugin-3.3.jar
- sonar-scm-git-plugin-1.1.jar
- sonar-scm-svn-plugin-1.1.jar

**Comment by chutch** [comment]
It doesn't seem to be strictly connected with AEM Rules. Does it start working again, when you delete AEM Rules plugin?

It's hard for me to investigate, since I did not encounter such situation. Could you pls pack your SQ instance and share it with me?

**Comment by andrexus** [comment]
Yes, if I remove plugin SQ can start again. Here is my [repo](https://github.com/andrexus/docker-aem-rules-for-sonarqube). If you have docker installed, you can simply type docker-compose up

**Comment by sebastianwr** [comment]
I had the issue with Java Plugin 3.0 and it worked again when I installed v3.5. I also used the pre-built jar from this repo instead of compiling it myself. I have SonarQube 5.1.2 here.

**Comment by andrexus** [comment]
@sebastianwr thanks for your tip. It resolved the issue
