### ISSUE TITLE
AEM-3 rule is not working with the sonarQube 7.1 with sonar scanner 3.1.0 and aem rules-0.10.jar

### ISSUE THREAD

**Issue by surenderkanaveni** [Cognifide/AEM-Rules-for-SonarQube#128]
Hi Team,

Thank you for these rules. We are using AEM cognifide rules but looks like AEM-3 rule is not picked by the sonar scanner. I purposefully broke AEM-1 rule and it's working as expected. 

Can you please share if you have any idea on why it's not working on the files ?

AEM-3 Non-thread safe object used as a field of Servlet / Filter etc.

Thanks,
Surender

**Comment by surenderkanaveni** [comment]
Thank you michal. Issue is with the sonar.java.libraries. After adding this property in my sonar-project.properties, i can see that issue got resolved and AEM-3 rule was reported.

**Comment by chutch** [comment]
That's great news. :-)

Please subscribe to https://github.com/Cognifide/AEM-Rules-for-SonarQube/releases.atom for new releases. We're aiming to add HTL support pretty soon.
