### ISSUE TITLE
Use of session based object in method annotated with @PostMapping should be added as exception for Rule AEM-9

### ISSUE THREAD

**Issue by michaltobiasz** [Cognifide/AEM-Rules-for-SonarQube#141]
Currently AEM-9 rule recognizes below code as issue.
```java
@PostMapping
public void afterCreated() {
     resourceResolver.map(request, currentResourcePath);
```
Expectation is to add except case when method uses @PostMapping annotation which is a correct usage of session objects

**Comment by chutch** [comment]
Closing as Slice rules has been deprecated.
