### ISSUE TITLE
Docker Image for AEM Rules

### ISSUE THREAD

**Issue by ahmed-musallam** [Cognifide/AEM-Rules-for-SonarQube#145]
I built this: https://github.com/ahmed-musallam/sonarqube-aem
a copy of the official sonar docker image with a slight change to include AEM Rules.

to run: 

```
docker run --rm -p 9000:9000 ahmedmusallam/sonarqube-aem:latest
```

Feel free to add this to the repo to get devs started quickly.
I will be writing an article on this soon as well :)

**Comment by chutch** [comment]
Hey @ahmed-musallam , 

thanks a lot, will add it to the readme. :-)

Send me the link to the article when it's live so I can tweet about it.

**Comment by ahmed-musallam** [comment]
@chutch I wrote a small post about it here: https://blogs.perficientdigital.com/2019/05/15/running-a-local-sonarqube-server-with-aem-rules/
