### ISSUE TITLE
Feature: Support for CloudManager Code Quality Rules in SQ

### ISSUE THREAD

**Issue by thedevopsguyblog** [Cognifide/AEM-Rules-for-SonarQube#233]
Hello,

I noticed that AMS have published the Code Quality rules used in Cloud Manager [here](https://experienceleague.adobe.com/docs/experience-manager-cloud-manager/assets/CodeQuality-rules-latest-AMS.xlsx?lang=en)

Is there a way we could 'import' these rules into SQ?

We'd like measure against these rules in conjunction with yours.

**Comment by tomasz-niedzwiedz-wttech** [comment]
Hi @thedevopsguyblog,

there are two ways to install new rules in SonarQube:
- Installing plugins from the Marketplace
- Dropping a JAR file into a folder on startup

The latter isn't possible in SonarCloud, just on-prem SonarQube.

The file you've attached lists a large number of generic rules, provided by multiple plugins (and some available OOTB). To support them, you'd have to install the relevant plugins and then enable the rules.

Enabling rules can be simplified by defining a [quality profile](https://docs.sonarqube.org/7.4/instance-administration/quality-profiles/) that you could manage as an XML file.

At a glance, you'd have to get a hold of a JAR file with Adobe's rules bundled (the ones in your spreadsheet that have the `CQRules` prefix). A search on the Marketplace only yields this project, as well as https://github.com/IBM/ibm-ix-aem-sonarqube-plugin, which I'm not familiar with.

**Comment by linlinas** [comment]
@toniedzwiedz could you please confirm if these rules are compatible with AEM as a Cloud Service CloudManger pipeline ?

**Comment by toniedzwiedz** [comment]
@linlinas as per the official documentation, these are the rules executed as part of Cloud Manager's code quality pipelines: https://experienceleague.adobe.com/docs/experience-manager-cloud-manager/content/using/custom-code-quality-rules.html?lang=en

The page links to an Excel document referencing a number of rules defined by this plugin, `AEM Rules:AEM-17`, `AEM Rules:AEM-6`, etc. So yes, Cloud Manager's code quality pipelines do use this plugin to some extent.

Bear in mind though, that there are a lot more rules used in Cloud Manager's predefined quality profile. This plugin only contains a small handful of those. I believe a great majority of the rules used come from SonarQube itself and some of its most popular plugins. Some are custom-made by Adobe and, to my knowledge, not open-sourced or available for download on their own.
