### ISSUE TITLE
Release a new binary version of plugin

### ISSUE THREAD

**Issue by ifourmanov** [Cognifide/AEM-Rules-for-SonarQube#31]
Hey there!
The last available binary version is 0.4 from 8 months old.
Can you please release a new jar version and mark it in github releases?

**Comment by chutch** [comment]
Hi Ilya, we're about to release 0.5 this week, we're testing everything is fine on all of our internal projects. Will let you know when that happens. Thanks for interest!

In case you don't want to wait: `mvn clean install` should do the work. :-)

**Comment by scotty6435** [comment]
Any progress with this? It would be extremely useful to have a jar produced and published to more easily integrate with our puppet provisioning for SonarQube.

**Comment by chutch** [comment]
Hi @scotty6435 @ifourmanov,

2 new versions of plugin have been released. 0.5 for SQ 4.5.7 & 0.6 for SQ 5.4

Let me know if that works for you.
