### ISSUE TITLE
Only first 8 rules are showing on sonarqube

### ISSUE THREAD

**Issue by adityarathore** [Cognifide/AEM-Rules-for-SonarQube#42]
I have imported a new jar file into plugins directory and after a restart it showing only first 8 rules on the sonarqube. Can you please tell why this is happening?

**Comment by chutch** [comment]
Hi @adityarathore ,

you may have installed 0.4 version of plugin, which did not include all the rules described. 

Please see freshly released plugin versions. :-)

0.5 for SQ 4.5.7 & 0.6 for SQ 5.4

**Comment by adityarathore** [comment]
I believe new jars are only added 15 days ago  :-) Thanks .

**Comment by chutch** [comment]
:-) Welcome!
