### ISSUE TITLE
Extend rule AEM-3 with additional classes

### ISSUE THREAD

**Issue by toniedzwiedz** [Cognifide/AEM-Rules-for-SonarQube#45]
[AEM-3](https://github.com/Cognifide/AEM-Rules-for-SonarQube/blob/master/src/main/java/com/cognifide/aemrules/checks/ThreadSafeFieldCheck.java) checks for the use of three non-thread-safe classes in field declarations in Servlets and Servlet Filters.

Out of the box, the [`ResourceResolver` can be adapted to several more classes:](https://docs.adobe.com/docs/en/aem/6-1/develop/platform/sling-adapters.html#Reference), including:

- `TagManager`
- `AssetManager`
- `UserManager`
- `Preferences`

To my knowledge, these also shouldn't be cached in a Sevlet/Filter field and It looks like including them in the AEM-3 rule would be very simple.

Not sure how many of those are likely to be used in this context. I believe some of these cases might be too absurd to even include (like caching a `User` object in a Servlet field) while some actually tend to be used in Servlets (`TagManager`, `AssetManager`)

Your thoughts?

**Comment by chutch** [comment]
Hi @toniedzwiedz,

thanks for pointing this out. It surely makes a lot of sense and actually the cost of adding all of these is close to none. I will add these classes. Thanks again!

**Comment by chutch** [comment]
Released: https://github.com/Cognifide/AEM-Rules-for-SonarQube/releases
