### ISSUE TITLE
Sling Model annotation with multiply adaptables property fail the build

### ISSUE THREAD

**Issue by AManuev** [Cognifide/AEM-Rules-for-SonarQube#46]
Hi!
I found that if class have multiply adaptables property, like
@Model(adaptables = {Resource.class, SlingHttpServletRequest.class})
it fail check with next message: 

[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.0.2:sonar (default-cli) on project xxx: SonarQube is unable to analyze file : 'x:\xx\xx\Foo.java': org.sonar.java.model.expression.NewArrayTreeImpl cannot be cast to org.sonar.plugins.java.api.tree.Me
mberSelectExpressionTree -> [Help 1]

Single property, like @Model(adaptables = SlingHttpServletRequest.class) works well.

Could someone check ? Thanks.

**Comment by chutch** [comment]
Hi Andrew!

Good catch, I will try to fix that this week. In the meantime, I would recommend to turn off this particular rule.

**Comment by AManuev** [comment]
Hi Michał! Thanks

**Comment by chutch** [comment]
Hi @AManuev 

I've fixed the mentioned issue - new version has been released and can be downloaded from here:

Please mind the dependencies: https://github.com/Cognifide/AEM-Rules-for-SonarQube/releases
