### ISSUE TITLE
Injector-based object is used outside the injector lifecycle

### ISSUE THREAD

**Issue by mchrominski** [Cognifide/AEM-Rules-for-SonarQube#52]
Consider following code.
```
ModelProvider modelProvider;
try (InjectorWithContext injector = InjectorUtil.getInjector(INJECTOR_NAME, request)) {
	modelProvider = injector.getInstance(ModelProvider.class);
	SomeSliceObject someSliceObject= injector.getInstance(SomeSliceObject.class);
}
someSliceObject.foo();
```

The reference for `someSliceObject` may fail depending on whether the injector has been closed already. The output is fairly indeterministic though.

Also, I believe a similar issue may appear out of Slice world for basically resource-based objects.

**Comment by toniedzwiedz** [comment]
@mchrominski Slice support was dropped with https://github.com/Cognifide/AEM-Rules-for-SonarQube/issues/143
Since there are no plans to include Slice-related features any more, I'm closing this one. If that's not okay with you, please let us know!
