### ISSUE TITLE
Clarify the phrase 'changeable method'

### ISSUE THREAD

**Issue by toniedzwiedz** [Cognifide/AEM-Rules-for-SonarQube#53]
I've had a look at the code while trying to figure out how one would go about implementing a rule and I noticed we're using the phrase _changeable method_ in context of the `ModifiableValueMap` rule (AEM-17) in both the docs and the code.

I find this choice of words confusing. Judging by the context, it seems to mean _a method that changes the state of an object_. I have never seen the phrase _changeable method_ used in this context. The use of the adjective seems to imply that it is the method is the subject of a change while in reality, it's the object on whose behalf the method is invoked that may or may not change.

Is there something I'm missing? I'm wondering where the phrase originated. If its use is accidental, how about referring to those methods as _mutators_ ?

**Comment by chutch** [comment]
Well, that's true. The meaning that we were trying to achieve is "a method that modifies a state of the object".

Do you have any particular wording in mind that would be the most clear?

**Comment by toniedzwiedz** [comment]
I'll raise a PR with a suggestion.

**Comment by toniedzwiedz** [comment]
I think the word _changeable_ got copied from the [Sling Javadoc](https://sling.apache.org/apidocs/sling7/org/apache/sling/api/resource/ModifiableValueMap.html) although in that specific instance, the context is actually correct and the word is used to describe the value map and not a method :)

**Comment by toniedzwiedz** [comment]
@chutch raised PR #54

**Comment by chutch** [comment]
Yeah, that seems to be a plausible explanation. :-) Thanks for PR!
