### ISSUE TITLE
ThreadSafeFieldCheck should cover EventHandlers and DS components

### ISSUE THREAD

**Issue by justinedelson** [Cognifide/AEM-Rules-for-SonarQube#56]
None of these are thread safe and should be included in the scope of this check.

Also, how come the Servlet interface isn't used for the Servlet checks?

**Comment by toniedzwiedz** [comment]
Indeed, the use of the two abstract classes instead of their common interface was a little naive. Especially considering the fact that one can register a servlet without subclassing any of those. Good spot.

Thanks for the contribution!

**Comment by chutch** [comment]
Thanks for great contribution! Of course it makes more sense to check against the interface.
