### ISSUE TITLE
Implement HTL Sensor to support HTL language

### ISSUE THREAD

**Issue by chutch** [Cognifide/AEM-Rules-for-SonarQube#63]
Implement a new sensor that will support writing new rules for [HTL language](https://docs.adobe.com/docs/en/htl/docs/expression-language.html). Consider list of following rules when making decision on how the analysis should be performed: 

< list of rules to be updated here >

(parser / regular expressions / jsoup / ?)

**Comment by deeprim** [comment]
Hello @chutch ,

I would like to propose few rules that I recognize to valuable:

* *error*: `data-sly-attribute` is used to render "javascript" attribute (e.g. onclick, onmousemove, etc), such attribute can not be processed via `data-sly-attribute` - nothing will be rendered
* *warning*: `data-sly-unwrap` inside `sly` tag. In such case `data-sly-unwrap` is simply ignored as it is redundant
* *warning*: Redundant HTL expression within `data-sly-use` or `data-sly-include`.
  HTL expression allows to pass some additional parameters but in case if no parameters passed it only brings redundant complexity and overhead for the runtime

For the example for those you could refer to [AEM Tools](https://github.com/aemtools/aemtools/tree/develop/inspection/src/main/kotlin/com/aemtools/inspection/html) plugin

BTW, to implement all aforementioned no grammar parsing is required (jsoup or regular expressions would suffice)

Cheers,
Dmytro

**Comment by chutch** [comment]
Hi @deeprim, thanks for the list of potential rules, looks good. 

Yeah, I was considering different options on how to approach new Sensor for HTL language and I'm torn apart, which way to choose. I'll keep that in mind. Have you considered contributing?
