### ISSUE TITLE
This plugin is not supported for SonarQube v6.3.1

### ISSUE THREAD

**Issue by dipen-sen** [Cognifide/AEM-Rules-for-SonarQube#66]
This plugin is not supported for SonarQube v6.3.1. After putting the jar in plugins folder sonar server does not start.

**Comment by chutch** [comment]
Hi @dipen-sen, thanks for rising the issue. The plugin wasn't tested on the SQ 6.3.1 yet. I will look into that this week.

**Comment by chutch** [comment]
Hi @dipen-sen, it will take some time to release and propagate version 0.9 through update console. In the meantime, you can download 0.9-RC3 from the releases section and add the jar manually into the plugins directory.

https://github.com/Cognifide/AEM-Rules-for-SonarQube/releases/tag/v0.9-RC3

**Comment by chutch** [comment]
Update: AEM Rules v0.9 plugin should be available through Update Center.
