### ISSUE TITLE
AEM Rules could not be activated

### ISSUE THREAD

**Issue by milindbangar79** [Cognifide/AEM-Rules-for-SonarQube#73]
Hi,

Using the latest SonarQube 6.7 LTS release and installed V0.9 of rule plugin.

While going through the AEM Repo, on the rules, not getting rule "Activate" option.

Login used : admin

Java Plugin Version with SQ67: 4.15.xx

[AEM Rules Activation.pdf](https://github.com/Cognifide/AEM-Rules-for-SonarQube/files/1542590/AEM.Rules.Activation.pdf)

Regards
Milind

**Comment by chutch** [comment]
Hi, @milindbangar79. It hasn't been tested with this version yet. Let me check that.

**Comment by chutch** [comment]
It seems that it is working correctly and we're able to activate rules. We can not reproduce it. Please check your permissions.
