### ISSUE TITLE
Technical Debt 

### ISSUE THREAD

**Issue by milindbangar79** [Cognifide/AEM-Rules-for-SonarQube#74]
Hi,

Please correct me, but did not see technical debt defined for the AEM rules.

Is it something which we have to define of our own?

Thanks
Milind

**Comment by chutch** [comment]
Thanks @milindbangar79 , I think it is possible to define it manually, but we will look into updating it as a part of the package.

**Comment by milindbangar79** [comment]
Hi @chutch ,

Can you please let me know how it can be defined on SonarQube directly or if there is something available to share.

Thanks in advance.

Regards
Milind

**Comment by chutch** [comment]
Fixed and tested on SQ 7.3
