### ISSUE TITLE
Pattern.compile should be moved to static final field in Servlets / Filters etc.

### ISSUE THREAD

**Issue by chutch** [Cognifide/AEM-Rules-for-SonarQube#76]
1. Check whether this rule is OOTB in SQ
2. Implement if not.

**Comment by GulderBone** [comment]
Rule already exists:
https://rules.sonarsource.com/java/tag/performance/RSPEC-4248

But it is not included in Cognifide way or Sonar way ruleset by default.
Issue can be closed.
